### ISSUE TITLE
About Regional Prompt

### ISSUE THREAD

**Issue by AtemSchiffer** [ffxvs/sd-webui-complete-setup#23]
Hi, this new version of stable diffusion seems to have problems with the installation of the regional prompt, here is the line of the problem. I would like to ask, is there a way to get the previous versions installed? I notice that there are also problems with the sound notification at the end and you can notice a bit of lag in the interface. Maybe it is the new version and not the paper. Thank you very much for everything!

⏳ Preparing...
It will take a little longer...
Launching WebUI...
Total VRAM 16109 MB, total RAM 45140 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4000 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using xformers cross attention
Using xformers attention for VAE
ControlNet preprocessor location: /notebooks/stable-diffusion-webui-forge/models/ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
CivitAI Browser+: Aria2 RPC started
*** Error loading script: attention.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: latent.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/latent.py", line 11, in <module>
        import scripts.attention as att
      File "/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

---
*** Error loading script: rp.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/rp.py", line 15, in <module>
        import scripts.attention
      File "/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

**Comment by ffxvs** [comment]
Hi, since the new Forge, Regional prompter extension doesn't work anymore.  
Although, someone has made an fork out of it, not all features work. You can remove the old extension and try this fork. 

[https://github.com/jessearodriguez/sd-forge-regional-prompter](https://github.com/jessearodriguez/sd-forge-regional-prompter)
> This is an attempt to port over the regional prompting webui extension over to forge. At the moment, only attention mode is usable. In addition, I have only tested sdxl models, please be aware that there is likely to be issues with other formats. Latent mode seems to generate without any console errors, but results in fused concepts. It will probably remain this way until someone more knowledgable than me fixes/improves/rewrites that code chunk in the future. Assume any posted issues on the main extension page apply to this one.

There is also an alternative to Regional Prompter called [Attention Couple](https://github.com/Haoming02/sd-forge-couple) which has similar functionality. You can install this extension from Extension list in the notebook.

I don't plan on supporting previous version of Forge as there would be a lot of compatibility issues to take into account. If you really need that one extension, I recommend sticking with the original Auto1111's WebUI.

<br>

> I notice that there are also problems with the sound notification at the end and you can notice a bit of lag in the interface.

I didn't experience any of this. Maybe this is due to a broken Regional prompter extension.  
Please let me know if the two extensions above can solve your problem! 👍
