### ISSUE TITLE
Gradio stuck loading

### ISSUE THREAD

**Issue by Totetoresano** [ffxvs/sd-webui-complete-setup#8]
Hello, I'm sorry for bothering you, but when I open the link to launch de WebUi (I'm using Forge), it gets stuck on the loading screen forever. Digging around I've seen that gradio has just been updated, I don't know if that might be the issue.
I've tried deleting the extensions that shows warnings as well but still no luck.
I'm using Paperspace and It was working fine until recently.
Here's the output of the launch Web UI cell:

```
⏳ Preparing...
It will take a little longer...
Launching Web UI...
Total VRAM 16117 MB, total RAM 30068 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro RTX 5000 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.float32
CUDA Stream Activated:  False
Using xformers cross attention
ControlNet preprocessor location: /notebooks/stable-diffusion-webui-forge/models/ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
person_yolov8n-seg.pt:   0%|                        | 0.00/6.78M [00:00<?, ?B/s]
face_yolov8s.pt:   0%|                              | 0.00/22.5M [00:00<?, ?B/s]

face_yolov8n.pt:   0%|                              | 0.00/6.23M [00:00<?, ?B/s]


hand_yolov8n.pt:   0%|                              | 0.00/6.24M [00:00<?, ?B/s]



person_yolov8n-seg.pt: 100%|████████████████| 6.78M/6.78M [00:00<00:00, 100MB/s]
face_yolov8n.pt: 100%|█████████████████████| 6.23M/6.23M [00:00<00:00, 73.9MB/s]
hand_yolov8n.pt: 100%|█████████████████████| 6.24M/6.24M [00:00<00:00, 97.3MB/s]
yolov8x-worldv2.pt:   0%|                            | 0.00/146M [00:00<?, ?B/s]
face_yolov8s.pt: 100%|██████████████████████| 22.5M/22.5M [00:00<00:00, 145MB/s]




person_yolov8s-seg.pt: 100%|████████████████| 23.9M/23.9M [00:00<00:00, 124MB/s]
yolov8x-worldv2.pt: 100%|█████████████████████| 146M/146M [00:00<00:00, 325MB/s]
[-] ADetailer initialized. version: 24.6.0, num models: 10
Model Downloader v1.0.8
Checking Directories...
all Directories already Created.
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-animatediff/scripts/animatediff_ui.py", line 19, in <module>
        class ToolButton(gr.Button, gr.components.FormComponent):
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 202, in __new__
        create_or_modify_pyi(component_class, name, events)
      File "/notebooks/stable-diffusion-webui-forge/modules/gradio_extensions.py", line 100, in gradio_component_meta_create_or_modify_pyi
        gradio_component_meta_create_or_modify_pyi_original(component_class, class_name, events)
      File "/notebooks/stable-diffusion-webui-forge/modules_forge/forge_canvas/canvas.py", line 16, in create_or_modify_pyi_org_patched
        return create_or_modify_pyi_org(component_class, class_name, events)
      File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 90, in create_or_modify_pyi
        source_file = Path(inspect.getfile(component_class))
      File "/usr/local/lib/python3.10/dist-packages/torch/package/package_importer.py", line 696, in _patched_getfile
        return _orig_getfile(object)
      File "/usr/lib/python3.10/inspect.py", line 786, in getfile
        raise TypeError('{!r} is a built-in class'.format(object))
    TypeError: <class 'animatediff_ui.py.ToolButton'> is a built-in class

---
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-animatediff/scripts/animatediff_ui.py:347: GradioDeprecationWarning: unexpected argument for Slider: precision
  self.params.batch_size = gr.Slider(
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/rp.py:103: GradioDeprecationWarning: unexpected argument for Image: tool
  polymask = gr.Image(label = "Do not upload here until bugfix",elem_id="polymask" + eladd,
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/rp.py:114: GradioDeprecationWarning: unexpected argument for Image: shape
  showmask = gr.Image(label = "Mask", shape=(IDIM, IDIM))
Loading weights [None] from /notebooks/stable-diffusion-webui-forge/models/Stable-diffusion/sdxl/autismmixSDXL_autismmixDPO.safetensors
2024-07-27 12:02:31,359 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 2816
*** Error executing callback ui_tabs_callback for /notebooks/stable-diffusion-webui-forge/extensions/sd-model-downloader/scripts/model-downloader.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui-forge/modules/script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "/notebooks/stable-diffusion-webui-forge/extensions/sd-model-downloader/scripts/model-downloader.py", line 310, in on_ui_tabs
        image.style(width=156, height=234)
    AttributeError: 'Image' object has no attribute 'style'. Did you mean: 'scale'?

---
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-cleaner/scripts/clean_up_tab.py:41: GradioDeprecationWarning: unexpected argument for Image: tool
  init_img_with_mask = gr.Image(label="Image for clean up with mask", show_label=False, elem_id="cleanup_img2maskimg", source="upload",
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-cleaner/scripts/clean_up_tab.py:41: GradioDeprecationWarning: unexpected argument for Image: brush_color
  init_img_with_mask = gr.Image(label="Image for clean up with mask", show_label=False, elem_id="cleanup_img2maskimg", source="upload",
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-cleaner/scripts/clean_up_tab.py:54: GradioDeprecationWarning: unexpected argument for Button: height
  clean_button = gr.Button("Clean Up", height=100)
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-cleaner/scripts/clean_up_tab.py:72: GradioDeprecationWarning: unexpected argument for Button: height
  send_to_cleaner_button = gr.Button("Send back To clean up", height=100)
Running on local URL:  https://link

To create a public link, set `share=True` in `launch()`.
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-animatediff/scripts/animatediff_ui.py:347: GradioDeprecationWarning: unexpected argument for Slider: precision
  self.params.batch_size = gr.Slider(
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/rp.py:103: GradioDeprecationWarning: unexpected argument for Image: tool
  polymask = gr.Image(label = "Do not upload here until bugfix",elem_id="polymask" + eladd,
/notebooks/stable-diffusion-webui-forge/extensions/sd-webui-regional-prompter/scripts/rp.py:114: GradioDeprecationWarning: unexpected argument for Image: shape
  showmask = gr.Image(label = "Mask", shape=(IDIM, IDIM))
IIB Database file has been successfully backed up to the backup folder.
Startup time: 35.1s (launcher: 2.8s, import torch: 10.8s, setup paths: 1.4s, initialize shared: 0.3s, other imports: 1.9s, list SD models: 0.8s, load scripts: 6.9s, create ui: 5.0s, gradio launch: 2.9s, add APIs: 2.1s, app_started_callback: 0.1s).
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Loading VAE weights specified in settings: /notebooks/stable-diffusion-webui-forge/models/VAE/sdxl/sdxl-vae-fp16-fix.safetensors
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  15996.41796875
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  12828.063270568848
Moving model(s) has taken 0.37 seconds
Model loaded in 30.5s (calculate hash: 1.1s, load weights from disk: 0.5s, forge load real models: 23.1s, load VAE: 2.9s, load textual inversion embeddings: 1.3s, calculate empty prompt: 1.4s).

```

**Comment by ffxvs** [comment]
Forge just got a new version that breaks a lot of extensions. So, for now we have to stick with the previous version that compatible with most extensions. I have pushed an update to fix this issue. Please download the latest notebook from the `Check for updates` cell.

**Comment by Totetoresano** [comment]
It works now, thank you very much for the swift response
